export default {
  DISPLAY_SINGLE: "DISPLAY_SINGLE",
  INCREMENT_LOOPS: "INCREMENT_LOOPS",
  MOVE_SUB_ONE: "MOVE_SUB_ONE",
  NEW_SUB: "NEW_SUB",
  ROTATE_SUB: "ROTATE_SUB",
  CREATE: "CREATE",
  UPDATE_TITLE: "UPDATE_TITLE",
};
