export const DISPLAY_SINGLE_TIMER = 'DISPLAY_SINGLE_TIMER'
export const ROTATE_SUB_TIMER = 'ROTATE_SUB_TIMER'
export const NEW_DISPLAY_TIMER = 'NEW_DISPLAY_TIMER'
export const NEW_SUB_TIMER = 'NEW_SUB_TIMER'
